"""add a alembic test table

Revision ID: 2c52205b6cc
Revises: 3cf6e18ce53
Create Date: 2014-11-12 11:26:36.069975

"""

# revision identifiers, used by Alembic.
revision = '2c52205b6cc'
down_revision = '3cf6e18ce53'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__alembictest__',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_alembic')
    op.drop_column('feedback', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('test_alembic',
    sa.Column('text', mysql.VARCHAR(length=12), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('__alembictest__')
    ### end Alembic commands ###
