"""alter table __alembictest__ 's column

Revision ID: adda012d9
Revises: 2c52205b6cc
Create Date: 2014-11-12 11:40:54.161867

"""

# revision identifiers, used by Alembic.
revision = 'adda012d9'
down_revision = '2c52205b6cc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('__alembictest__', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('__alembictest__', 'text',
               existing_type=mysql.VARCHAR(length=123),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('feedback', 'processed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop', 'have_offline_entity',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop', 'have_wx_mp',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('system_order', 'have_more_data',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('system_order', 'have_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_order', 'have_read',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('system_order', 'have_more_data',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('shop', 'have_wx_mp',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('shop', 'have_offline_entity',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('feedback', 'processed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('__alembictest__', 'text',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=123),
               existing_nullable=True)
    op.alter_column('__alembictest__', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
