fruit_types = [{'name': '梨子', 'code': 'Li'} ,
               {'name': '西瓜', 'code': 'Xg'} ,
               {'name': '芒果', 'code': 'Mg'} ,
               {'name': '荔枝', 'code': 'Lz'} ,
               {'name': '火龙果', 'code': 'Hlg'} ,
               {'name': '青苹果', 'code': 'Qpg'} ,
               {'name': '苹果', 'code': 'Pg'} ,
               {'name': '青梨', 'code': 'Qli'} ,
               {'name': '葡萄', 'code': 'Pt'} ,
               {'name': '提子', 'code': 'Tz'} ,
               {'name': '小金橘', 'code': 'Xjj'} ,
               {'name': '冬枣', 'code': 'Dz'} ,
               {'name': '橘子', 'code': 'Jz'} ,
               {'name': '小番茄', 'code': 'Xfq'} ,
               {'name': '柠檬', 'code': 'Nm'} ,
               {'name': '榴莲', 'code': 'Ll'} ,
               {'name': '哈密瓜', 'code': 'Hmg'} ,
               {'name': '猕猴桃', 'code': 'Mht'} ,
               {'name': '橙子', 'code': 'Cz'} ,
               {'name': '柚子', 'code': 'Yz'} ,
               {'name': '香瓜', 'code': 'Xiangg'} ,
               {'name': '木瓜', 'code': 'Mug'} ,
               {'name': '香蕉', 'code': 'Xj'} ,
               {'name': '石榴', 'code': 'Sl'} ,
               {'name': '水蜜桃', 'code': 'Smt'} ,
               {'name': '椰子', 'code': 'Yez'} ,
               {'name': '白地瓜', 'code': 'Bdg'} ,
               {'name': '菠萝蜜', 'code': 'Blm'} ,
               {'name': '山楂', 'code': 'Sz'} ,
               {'name': '桂圆', 'code': 'Gy'} ,
               {'name': '枇杷', 'code': 'Pp'} ,
               {'name': '红枣', 'code': 'Hz'} ,
               {'name': '菠萝', 'code': 'Bl'} ,
               {'name': '柿子', 'code': 'Shiz'} ,
               {'name': '山竹', 'code': 'Shanzhu'} ,
               {'name': '帝皇柑', 'code': 'Dhg'} ,
               {'name': '草莓', 'code': 'Cm'} ,
               {'name': '雪莲果', 'code': 'Xlg'} ,
               {'name': '甘蔗', 'code': 'Gz'} ,
               {'name': '黑布林', 'code': 'Hbl'} ,
               {'name': '杨桃', 'code': 'Yangt'} ,
               {'name': '核桃', 'code': 'Het'} ,
]

charge_types = [
    {"id":1,
     "good_name":"森果商城系统1.0（三个月套餐）",
     "month":3,
     "price":588,
     "description":"588元/三个月"},
    {"id":2,
     "good_name":"森果商城系统1.0（六个月套餐）",
     "month":6,
     "price":988,
     "description":"988元/六个月"},
    {"id":3,
     "good_name":"森果商城系统1.0（十二个月套餐）",
     "month":12,
     "price":1788,
     "description":"1788元/十二个月"}
]
